module.exports = function help(options) {
  console.log();
  console.log('*lm* helps you to deal with local npm modules.');
  console.log('It installs local modules and it\'s dependencies, e.g. useful in production, ');
  console.log('and links them to have always up to date modules e.g. during development. ');
  console.log();
  console.log('Usage: lm <command> [options]');
  console.log();
  console.log('lm -h      show help');
  console.log('lm -v      print lm version');
  console.log();
  console.log('Commands: ');
  console.log();
  console.log('install    temporary adds the local module to the package.json, runs `npm install`, and removes them from package.json again.');
  console.log('uninstall  removes the local modules from the package.json, and runs `npm prune`, to remove the unneeded but installed modules.');
  console.log('link       links the local modules into the `node_modules` folder.');
  console.log('unlink     removes links of the local modules inside the `node_modules` folder.');
  console.log('add        adds the local modules to the package.json');
  console.log('remove     removes the local modules from the package.json');
  console.log();
  console.log('Options: ');
  console.log('--dir      local module dirname default:`local_modules`');
  console.log('--tmp      temporary package.json file ending during install');
  console.log('--force    forced action: remove stuff, before copying or linking');
  console.log('');
};